### ISSUE TITLE
www. url support

### ISSUE THREAD

**Issue by zbjornson** [stephenplusplus/gitnpm#8]
Not sure if this goes here or in google-cloud-node.

There are two links in the google-cloud-node docs that link to www.gitnpm.com, but www does not seem to work.
- https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/master/storage/file?method=createReadStream links to fast-crc32c
- https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/master/storage/file?method=createWriteStream links to fast-crc32c

**Comment by stephenplusplus** [comment]
Ooh, good one. The DNS was pointed in two different directions, one to an old AE project and the other to the right one. This is now fixed up, thanks!
